// Copyright (c) 2026 Anomly, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// bposit_quire_sfpu_add — the FIRST SFPU-vectorized milestone of Anomly's EXACT
// 256-bit b-posit16 Kulisch quire on Blackhole: a LANE-PARALLEL exact q256_add.
//
// 32 INDEPENDENT 256-bit accumulators run across the SFPU's 32 lanes. The compute
// kernel (kernels/compute/sfpu_q256_add.cpp) holds the quire as 8 limb-VECTORS
// (one Int32 tile per limb; lane j of each tile = limb of lane j's quire) and adds
// a second 8-limb set, propagating carry limb-to-limb across all 32 lanes via an
// unsigned-less-than carry detect. The result must be BIT-IDENTICAL per lane to
// the scalar reference q256_add (kernel/bp16_quire.h:62-65).
//
// Host structure / golden gate mirror the PROVEN sibling example
// programming_examples/bposit_quire_reduce/bposit_quire_reduce.cpp:
//   - bake a golden of 32 lanes x (q[8], x[8], expected[8]) — GENERATED by
//     gen_sfpu_add_golden.py and re-derived HERE at startup by calling the REAL C
//     q256_add over each lane (belt-and-suspenders: a drifted golden is caught
//     before the device run), then
//   - dispatch the SFPU compute kernel, read back the 8x32 result, and gate
//     bit-exact lane-by-lane.
//
// Device idioms (unit mesh, MeshBuffer, CreateKernel, CB Int32, init_sfpu/copy/
// pack) are taken idiom-for-idiom from custom_sfpi_add/custom_sfpi_add.cpp and
// eltwise_sfpu — see BUILD_NOTES.md for the exact file:line grounding.

#include <fmt/ostream.h>
#include <tt-metalium/host_api.hpp>
#include <tt-metalium/device.hpp>
#include <tt-metalium/distributed.hpp>
#include <tt-metalium/tensor_accessor_args.hpp>
#include <tt-metalium/constants.hpp>
#include <cstdint>
#include <cstdlib>
#include <map>
#include <string>
#include <vector>
#include <iostream>
#include <iomanip>

// Baked golden: 32 lanes x (q[8], x[8], expected[8]), layout [limb][lane].
#include "sfpu_add_golden_cases.h"

// Host self-check reuses the SAME exact numerics the milestone targets: the real
// scalar q256_add from the scalar reference kernels (targets/blackhole/kernel) (proven byte-identical x86 == qemu-rv32 ==
// ttsim-BRISC). Suppress unused-function (freestanding header, strict tt-metal).
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#include "../../kernel/bp16_quire.h"
#pragma GCC diagnostic pop

using namespace tt;
using namespace tt::tt_metal;

#ifndef OVERRIDE_KERNEL_PREFIX
#define OVERRIDE_KERNEL_PREFIX ""
#endif

// One Int32 tile = 32x32 = 1024 elements. We replicate each lane's limb value
// across ALL 32 rows so the SFPU produces the same per-lane answer in every face;
// the host reads lane j back from row 0, column j.
static constexpr uint32_t TILE_W = 32;
static constexpr uint32_t TILE_H = 32;
static constexpr uint32_t TILE_HW = TILE_W * TILE_H;  // 1024

// Build a tile where element (r*32 + c) holds lane c's value for this limb.
static std::vector<uint32_t> make_limb_tile(const uint32_t lane_vals[QSFPU_LANES]) {
    std::vector<uint32_t> tile(TILE_HW);
    for (uint32_t r = 0; r < TILE_H; ++r)
        for (uint32_t c = 0; c < TILE_W; ++c)
            tile[r * TILE_W + c] = lane_vals[c];  // QSFPU_LANES == TILE_W == 32
    return tile;
}

int main() {
    static_assert(QSFPU_LANES == 32, "this milestone is exactly 32 lanes (one SFPU width)");
    static_assert(QSFPU_LIMBS == 8, "256-bit quire = 8 x u32 limbs");
    // Limbs per compute lease/batch (must match QSFPU_BATCH in the compute kernel): the
    // 8-limb ripple is split into 2 leases of 4 so the live INT32 dst footprint per lease
    // (4 OUT + CARRY + Q + X = 7) stays within the SyncFull/accum=true budget of 8.
    constexpr int QSFPU_BATCH = 4;

    // ---- host self-check: re-derive the golden from the REAL scalar q256_add ---
    // For each lane, run the exact C q256_add(q, x) and confirm it equals the baked
    // expected. A drifted baked golden is caught here before any device dispatch.
    {
        bool golden_ok = true;
        for (int lane = 0; lane < QSFPU_LANES; ++lane) {
            unsigned q[8], x[8];
            for (int l = 0; l < QSFPU_LIMBS; ++l) {
                q[l] = QSFPU_Q[l][lane];
                x[l] = QSFPU_X[l][lane];
            }
            q256_add(q, x);  // EXACT scalar reference (bp16_quire.h:62-65), in place
            for (int l = 0; l < QSFPU_LIMBS; ++l) {
                if (q[l] != QSFPU_EXP[l][lane]) {
                    golden_ok = false;
                    std::cout << "  self-check lane " << lane << " limb " << l
                              << " ref=0x" << std::hex << q[l]
                              << " baked=0x" << QSFPU_EXP[l][lane] << std::dec << "\n";
                }
            }
        }
        if (!golden_ok) {
            std::cout << "FAIL: baked SFPU-add golden disagrees with the real scalar "
                         "q256_add (host self-check) — regenerate gen_sfpu_add_golden.py\n";
            return 1;
        }
    }

    // ---- device setup (unit mesh, idiom from custom_sfpi_add.cpp:31-34) --------
    auto mesh_device = distributed::MeshDevice::create_unit_mesh(0);
    auto& cq = mesh_device->mesh_command_queue();
    distributed::MeshWorkload workload;
    auto device_range = distributed::MeshCoordinateRange(mesh_device->shape());
    auto program = CreateProgram();
    constexpr CoreCoord core = {0, 0};

    constexpr uint32_t tile_bytes = sizeof(uint32_t) * TILE_HW;

    // DRAM buffers: Q (8 tiles), X (8 tiles), ZERO (1 tile), OUT (8 tiles). One
    // page == one tile, so noc_async_read_page(limb, ...) addresses each limb tile.
    auto mk = [&](uint32_t n_tiles) {
        distributed::DeviceLocalBufferConfig lc{.page_size = tile_bytes, .buffer_type = BufferType::DRAM};
        distributed::ReplicatedBufferConfig bc{.size = (size_t)n_tiles * tile_bytes};
        return distributed::MeshBuffer::create(bc, lc, mesh_device.get());
    };
    auto q_dram = mk(QSFPU_LIMBS);
    auto x_dram = mk(QSFPU_LIMBS);
    auto zero_dram = mk(1);
    auto out_dram = mk(QSFPU_LIMBS);

    // ---- circular buffers, Int32 (custom_sfpi_add.cpp:81-99, but DataFormat::Int32
    //      per add_int_sfpu.h:25 supported formats) -------------------------------
    auto make_cb = [&](CBIndex idx, uint32_t n_tiles) {
        CircularBufferConfig cfg(n_tiles * tile_bytes, {{idx, tt::DataFormat::Int32}});
        cfg.set_page_size(idx, tile_bytes);
        CreateCircularBuffer(program, core, cfg);
    };
    make_cb(CBIndex::c_0, QSFPU_LIMBS);   // Q limbs
    make_cb(CBIndex::c_1, QSFPU_LIMBS);   // X limbs
    make_cb(CBIndex::c_2, 1);             // ZERO seed (carry init for batch 0)
    make_cb(CBIndex::c_3, 1);             // CARRY-MID: limb-3 carry-out, batch 0 -> batch 1
    make_cb(CBIndex::c_16, QSFPU_LIMBS);  // OUT limbs
    // ONE carry CB (c_3): the carry crosses exactly ONE lease boundary (batch 0 -> batch
    // 1). Within each 4-limb batch the 32-lane carry lives in a single persistent dst
    // slot (updated in place, Welford-style) — never a CB. The single carry-mid tile is
    // written by batch 0 and read by batch 1 (different leases), so there is no in-lease
    // self-alias. Each 4-limb batch keeps 7 live INT32 dst tiles (OUT0..3,CARRY,Q,X) <= 8.

    // ---- kernels --------------------------------------------------------------
    std::vector<uint32_t> reader_ct_args;
    TensorAccessorArgs(*q_dram->get_backing_buffer()).append_to(reader_ct_args);
    TensorAccessorArgs(*x_dram->get_backing_buffer()).append_to(reader_ct_args);
    TensorAccessorArgs(*zero_dram->get_backing_buffer()).append_to(reader_ct_args);
    auto reader = CreateKernel(
        program, OVERRIDE_KERNEL_PREFIX "bposit_quire_sfpu_add/kernels/dataflow/read_limbs.cpp", core,
        DataMovementConfig{.processor = DataMovementProcessor::RISCV_0, .noc = NOC::RISCV_0_default,
                           .compile_args = reader_ct_args});

    std::vector<uint32_t> writer_ct_args;
    TensorAccessorArgs(*out_dram->get_backing_buffer()).append_to(writer_ct_args);
    auto writer = CreateKernel(
        program, OVERRIDE_KERNEL_PREFIX "bposit_quire_sfpu_add/kernels/dataflow/write_limbs.cpp", core,
        DataMovementConfig{.processor = DataMovementProcessor::RISCV_1, .noc = NOC::RISCV_1_default,
                           .compile_args = writer_ct_args});

    // ROOT-CAUSE FIX (2026-06-24): INT32/32-bit data REQUIRES fp32_dest_acc_en = TRUE.
    // DEST is physically a 16-bit register file; loading 32-bit tiles into a DEST
    // configured for 16-bit (fp32_dest_acc_en=false) produces TILE-ALIGNED CORRUPTION
    // (binary_ng_program_factory.cpp:714-721, ternary_program_factory.cpp:1253-1254 —
    // every shipped INT32 SFPU op sets this true for Int32/UInt32). With it FALSE, the
    // SFPU compute mis-strided DEST: limbs 0-2 aliased OK, limbs 3-7 read 0, and the
    // carry showed a period-4 artifact — pure 16/32-bit DEST-stride mismatch (took the
    // gate 8/32 -> 14/32 once corrected).
    //
    // With fp32_dest_acc_en=true the INT32 DEST budget HALVES (32-bit accum path):
    //   get_dest_max_tiles<SyncFull, accum=true, Tile32x32> = (1024>>1)>>6 = 8 tiles
    //   (ckernel.h:835-842 / tensix_types.h:191-194). The compute kernel splits the
    //   8-limb ripple into TWO leases of 4 limbs (4 OUT + CARRY + Q + X = 7 <= 8 live),
    //   with the carry held IN a single persistent dst slot (in-place ripple) within each
    //   lease and crossing the one lease boundary via a single carry-mid CB tile.
    //   dst_full_sync_en=true => SyncFull, which pins the dst base at 0 (no per-acquire
    //   half-flip), so both leases share one stable slot map.
    // INPUT-READBACK DIAGNOSTIC (4+4 batches; Q/X are reused scratch, so at pack time
    // they hold the batch's LAST limb = limb 3 / limb 7): ECHO_INPUT=1 -> cb_out tiles
    // 0..3 all = loaded Q of limb 3, tiles 4..7 = loaded Q of limb 7; =2 same for X; =3
    // -> each batch's final carry. Unset/0 = normal exact add. The JIT recompiles for the
    // chosen define, so no source edit is needed — just rerun with the env var.
    std::map<std::string, std::string> compute_defines;
    if (const char* echo = std::getenv("ECHO_INPUT")) {
        if (echo[0] != '\0' && echo[0] != '0') compute_defines["ECHO_INPUT"] = echo;
    }
    // ECHO_TRACE=1: BATCH-boundary CARRY probe. cb_out is repurposed — every tile of a
    // batch = that batch's FINAL carry-out (carry after limb 3 for tiles 0..3, carry
    // after limb 7 for tiles 4..7). Distinguishes an in-batch ripple failure from a
    // cross-batch carry-handoff failure (the carry-mid CB).
    if (const char* tr = std::getenv("ECHO_TRACE")) {
        if (tr[0] != '\0' && tr[0] != '0') compute_defines["ECHO_TRACE"] = tr;
    }
    auto compute = CreateKernel(
        program, OVERRIDE_KERNEL_PREFIX "bposit_quire_sfpu_add/kernels/compute/sfpu_q256_add.cpp", core,
        ComputeConfig{.fp32_dest_acc_en = true, .dst_full_sync_en = true, .defines = compute_defines});

    SetRuntimeArgs(program, reader, core,
                   {(uint32_t)q_dram->address(), (uint32_t)x_dram->address(),
                    (uint32_t)zero_dram->address(), (uint32_t)QSFPU_LIMBS});
    SetRuntimeArgs(program, writer, core, {(uint32_t)out_dram->address(), (uint32_t)QSFPU_LIMBS});
    SetRuntimeArgs(program, compute, core, {});

    // ---- marshal inputs: 8 Q-limb tiles, 8 X-limb tiles, 1 zero tile ----------
    std::vector<uint32_t> q_host(QSFPU_LIMBS * TILE_HW), x_host(QSFPU_LIMBS * TILE_HW);
    for (int l = 0; l < QSFPU_LIMBS; ++l) {
        auto qt = make_limb_tile(QSFPU_Q[l]);
        auto xt = make_limb_tile(QSFPU_X[l]);
        std::copy(qt.begin(), qt.end(), q_host.begin() + (size_t)l * TILE_HW);
        std::copy(xt.begin(), xt.end(), x_host.begin() + (size_t)l * TILE_HW);
    }
    std::vector<uint32_t> zero_host(TILE_HW, 0u);

    distributed::EnqueueWriteMeshBuffer(cq, q_dram, q_host, /*blocking=*/false);
    distributed::EnqueueWriteMeshBuffer(cq, x_dram, x_host, /*blocking=*/false);
    distributed::EnqueueWriteMeshBuffer(cq, zero_dram, zero_host, /*blocking=*/false);

    workload.add_program(device_range, std::move(program));
    distributed::EnqueueMeshWorkload(cq, workload, /*blocking=*/false);

    std::vector<uint32_t> out_host(QSFPU_LIMBS * TILE_HW, 0u);
    distributed::EnqueueReadMeshBuffer(cq, out_host, out_dram, /*blocking=*/true);

    // ---- INPUT-READBACK DIAGNOSTIC (always prints lanes 7 & 16) ----------------
    // Echo what the kernel reads back from cb_out. In a normal build cb_out holds the
    // SUM; build the COMPUTE kernel with -DECHO_INPUT=1 (or 2) and cb_out instead
    // holds the Q (or X) limb the kernel actually loaded — so this dump shows, per
    // limb, whether the high limbs of the NEGATIVE operands (lanes 7,12: golden
    // 0xffffffff) arrive at the SFPU or read as 0. With ECHO_INPUT compare to
    // QSFPU_Q/QSFPU_X; without it (normal), compare to QSFPU_EXP.
    {
        // Mode is chosen at RUNTIME by env (it gates the kernel JIT define, not the
        // host TU), so read it here too for the label / interpretation.
        const char* echo = std::getenv("ECHO_INPUT");
        const char* trace = std::getenv("ECHO_TRACE");
        const bool tr = (trace && trace[0] && trace[0] != '0');
        const int echo_n = (echo && echo[0] && echo[0] != '0') ? std::atoi(echo) : 0;
        std::cout << "  [diag] mode: "
                  << (tr ? "ECHO_TRACE=1 (cb_out[0..3]=carry-after-limb3, [4..7]=carry-after-limb7)"
                         : echo_n == 1 ? "ECHO_INPUT=1 (cb_out[0..3]=Q limb3, [4..7]=Q limb7)"
                         : echo_n == 2 ? "ECHO_INPUT=2 (cb_out[0..3]=X limb3, [4..7]=X limb7)"
                         : echo_n == 3 ? "ECHO_INPUT=3 (cb_out=per-batch final carry)"
                                       : "normal (cb_out==exact sum)")
                  << "\n";

        // Compute the EXPECTED per-limb carry history (scalar reference) for the trace
        // interpretation — so the [diag] dump shows golden carry vs device carry.
        const int diag_lanes[] = {7, 12, 15, 16, 18, 19};
        for (int lane : diag_lanes) {
            // golden running carry after each limb
            uint32_t exp_carry[QSFPU_LIMBS] = {0};
            {
                unsigned long long c = 0;
                for (int l = 0; l < QSFPU_LIMBS; ++l) {
                    unsigned long long t =
                        (unsigned long long)QSFPU_Q[l][lane] + QSFPU_X[l][lane] + c;
                    c = t >> 32;
                    exp_carry[l] = (uint32_t)c;  // carry-out of limb l == carry-in of l+1
                }
            }
            std::cout << "  [diag] lane " << lane << ":\n";
            for (int l = 0; l < QSFPU_LIMBS; ++l) {
                uint32_t dev = out_host[(size_t)l * TILE_HW + 0 * TILE_W + lane];
                std::cout << "    limb " << l
                          << " dev=0x" << std::hex << std::setw(8) << std::setfill('0') << dev
                          << "  Q=0x" << std::setw(8) << std::setfill('0') << QSFPU_Q[l][lane]
                          << "  X=0x" << std::setw(8) << std::setfill('0') << QSFPU_X[l][lane]
                          << "  EXP=0x" << std::setw(8) << std::setfill('0') << QSFPU_EXP[l][lane]
                          << std::dec;
                if (tr) {
                    // ECHO_TRACE packs the BATCH-FINAL carry into every tile of the batch:
                    // tiles 0..3 = carry-out of limb 3, tiles 4..7 = carry-out of limb 7.
                    const int batch_last = (l < QSFPU_BATCH) ? (QSFPU_BATCH - 1) : (QSFPU_LIMBS - 1);
                    std::cout << "  [trace] batch-carry dev=" << dev
                              << " exp(after limb " << batch_last << ")=" << exp_carry[batch_last];
                }
                std::cout << "\n";
            }
        }
    }

    // ---- gate bit-exact, lane-by-lane -----------------------------------------
    // Read lane j of limb l from row 0, column j of OUT tile l.
    int bad_lanes = 0;
    int first_bad = -1;
    for (int lane = 0; lane < QSFPU_LANES; ++lane) {
        bool lane_ok = true;
        for (int l = 0; l < QSFPU_LIMBS; ++l) {
            uint32_t dev = out_host[(size_t)l * TILE_HW + /*row0*/ 0 * TILE_W + lane];
            if (dev != QSFPU_EXP[l][lane]) {
                lane_ok = false;
                if (bad_lanes < 8)
                    std::cout << "  lane " << lane << " limb " << l
                              << " device=0x" << std::hex << std::setw(8) << std::setfill('0') << dev
                              << " golden=0x" << std::setw(8) << std::setfill('0') << QSFPU_EXP[l][lane]
                              << std::dec << "\n";
            }
        }
        if (!lane_ok) {
            ++bad_lanes;
            if (first_bad < 0) first_bad = lane;
        }
    }

    const int good = QSFPU_LANES - bad_lanes;
    const bool pass = (bad_lanes == 0);
    if (pass) {
        std::cout << "PASS: SFPU lane-parallel q256_add, " << good << "/" << QSFPU_LANES
                  << " lanes bit-exact (" << QSFPU_LIMBS << " limbs each)\n";
    } else {
        std::cout << "FAIL: SFPU lane-parallel q256_add, " << good << "/" << QSFPU_LANES
                  << " lanes bit-exact (" << QSFPU_LIMBS << " limbs each); first bad lane "
                  << first_bad << "\n";
    }

    mesh_device->close();
    return pass ? 0 : 1;
}
