cmake_minimum_required(VERSION 3.22...4.2)
project(metal_example_bposit_quire_matmul_multicore_perf)
add_executable(metal_example_bposit_quire_matmul_multicore_perf)
target_sources(metal_example_bposit_quire_matmul_multicore_perf PRIVATE bposit_quire_matmul_multicore_perf.cpp)
if(NOT TARGET TT::Metalium)
    find_package(TT-Metalium REQUIRED)
endif()
target_link_libraries(metal_example_bposit_quire_matmul_multicore_perf PUBLIC TT::Metalium)
if(TARGET TT::CommonPCH)
    tt_reuse_precompile_headers(metal_example_bposit_quire_matmul_multicore_perf TT::CommonPCH)
endif()
