/* Copyright (c) 2026 Anomly, Inc.
 * SPDX-License-Identifier: Apache-2.0 */
/* quire_gradient_cases.h — GENERATED by gen_gradient_golden.py.
 * DO NOT hand-edit. Training-realistic gradient-accumulation vectors
 * g = Sum_t d_t where a large early contribution inflates the running
 * accumulator to magnitude M, so each subsequent tiny per-step gradient
 * falls below ULP(M) and is LOST by an IEEE fp32 running sum (the
 * swamping / gradient-underflow problem). The EXACT 256-bit b-posit16
 * quire keeps every contribution and recovers the tiny-tail mass.
 *
 * Ground truth from the oracle's exact Fraction arithmetic
 * (bposit16_reference.py); fp32 baseline = genuine IEEE-754 binary32 RTNE
 * running sum (struct round-trip).
 *
 * Per case the host gates: (1) device quire limbs + bp16 readout ==
 * baked exact quire/readout (quire error 0 vs exact gradient); (2) device
 * fp32 running-sum bits == baked fp32 bits, and != the exact gradient
 * bits (fp32 genuinely loses tail mass). Self-checked against the reused C
 * headers at startup before any device run.
 */
#ifndef QUIRE_GRADIENT_CASES_H
#define QUIRE_GRADIENT_CASES_H

#include <cstdint>

#define QGRAD_NCASES 4

/* ---- case 0: grad_accum_T64 ---- */
/*   +2^14 spike, 64x +2^-14 tiny per-step grads, -2^14, +1/128 coarse grad  (running sum M=2^14; each tau<ULP(M); exact g=0.01171875) */
/*   exact g = 3/256 = 0.01171875 ; quire readout 0x2600 = 0.01171875 (EXACT) ; fp32 running sum = 0.0078125 (0x3c000000) ; fp32 LOSES 33.3% of g */
static const int32_t QGRAD_GRAD_ACCUM_T64_CODES[] = {
    0x6c00, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x9400, 0x2400,
};
static const int QGRAD_GRAD_ACCUM_T64_N = (int)(sizeof(QGRAD_GRAD_ACCUM_T64_CODES)/sizeof(QGRAD_GRAD_ACCUM_T64_CODES[0]));
static const int QGRAD_GRAD_ACCUM_T64_T = 64;  /* number of tiny per-step grads */
static const uint32_t QGRAD_GRAD_ACCUM_T64_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0x03000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char QGRAD_GRAD_ACCUM_T64_QUIRE_HEX[] = "0000000000000000000000030000000000000000000000000000000000000000";
static const int32_t QGRAD_GRAD_ACCUM_T64_READOUT_BP16 = 0x2600;
static const uint32_t QGRAD_GRAD_ACCUM_T64_FP32_BITS = 0x3c000000u;  /* genuine fp32 running sum (loses tail) */
static const uint32_t QGRAD_GRAD_ACCUM_T64_EXACT_FP32_BITS = 0x3c400000u;  /* fp32(exact gradient) -- the target fp32 missed */
static const int64_t QGRAD_GRAD_ACCUM_T64_EXACT_NUM = 3LL;
static const int64_t QGRAD_GRAD_ACCUM_T64_EXACT_DEN = 256LL;
static const char QGRAD_GRAD_ACCUM_T64_NAME[] = "grad_accum_T64";

/* ---- case 1: grad_accum_T128 ---- */
/*   +2^14 spike, 128x +2^-14 tiny per-step grads, -2^14, +1/128 coarse grad  (running sum M=2^14; each tau<ULP(M); exact g=0.015625) */
/*   exact g = 1/64 = 0.015625 ; quire readout 0x2800 = 0.015625 (EXACT) ; fp32 running sum = 0.0078125 (0x3c000000) ; fp32 LOSES 50.0% of g */
static const int32_t QGRAD_GRAD_ACCUM_T128_CODES[] = {
    0x6c00, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x9400, 0x2400,
};
static const int QGRAD_GRAD_ACCUM_T128_N = (int)(sizeof(QGRAD_GRAD_ACCUM_T128_CODES)/sizeof(QGRAD_GRAD_ACCUM_T128_CODES[0]));
static const int QGRAD_GRAD_ACCUM_T128_T = 128;  /* number of tiny per-step grads */
static const uint32_t QGRAD_GRAD_ACCUM_T128_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0x04000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char QGRAD_GRAD_ACCUM_T128_QUIRE_HEX[] = "0000000000000000000000040000000000000000000000000000000000000000";
static const int32_t QGRAD_GRAD_ACCUM_T128_READOUT_BP16 = 0x2800;
static const uint32_t QGRAD_GRAD_ACCUM_T128_FP32_BITS = 0x3c000000u;  /* genuine fp32 running sum (loses tail) */
static const uint32_t QGRAD_GRAD_ACCUM_T128_EXACT_FP32_BITS = 0x3c800000u;  /* fp32(exact gradient) -- the target fp32 missed */
static const int64_t QGRAD_GRAD_ACCUM_T128_EXACT_NUM = 1LL;
static const int64_t QGRAD_GRAD_ACCUM_T128_EXACT_DEN = 64LL;
static const char QGRAD_GRAD_ACCUM_T128_NAME[] = "grad_accum_T128";

/* ---- case 2: grad_accum_T192 ---- */
/*   +2^14 spike, 192x +2^-14 tiny per-step grads, -2^14, +1/128 coarse grad  (running sum M=2^14; each tau<ULP(M); exact g=0.01953125) */
/*   exact g = 5/256 = 0.01953125 ; quire readout 0x2900 = 0.01953125 (EXACT) ; fp32 running sum = 0.0078125 (0x3c000000) ; fp32 LOSES 60.0% of g */
static const int32_t QGRAD_GRAD_ACCUM_T192_CODES[] = {
    0x6c00, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x9400, 0x2400,
};
static const int QGRAD_GRAD_ACCUM_T192_N = (int)(sizeof(QGRAD_GRAD_ACCUM_T192_CODES)/sizeof(QGRAD_GRAD_ACCUM_T192_CODES[0]));
static const int QGRAD_GRAD_ACCUM_T192_T = 192;  /* number of tiny per-step grads */
static const uint32_t QGRAD_GRAD_ACCUM_T192_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0x05000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char QGRAD_GRAD_ACCUM_T192_QUIRE_HEX[] = "0000000000000000000000050000000000000000000000000000000000000000";
static const int32_t QGRAD_GRAD_ACCUM_T192_READOUT_BP16 = 0x2900;
static const uint32_t QGRAD_GRAD_ACCUM_T192_FP32_BITS = 0x3c000000u;  /* genuine fp32 running sum (loses tail) */
static const uint32_t QGRAD_GRAD_ACCUM_T192_EXACT_FP32_BITS = 0x3ca00000u;  /* fp32(exact gradient) -- the target fp32 missed */
static const int64_t QGRAD_GRAD_ACCUM_T192_EXACT_NUM = 5LL;
static const int64_t QGRAD_GRAD_ACCUM_T192_EXACT_DEN = 256LL;
static const char QGRAD_GRAD_ACCUM_T192_NAME[] = "grad_accum_T192";

/* ---- case 3: grad_accum_T256 ---- */
/*   +2^14 spike, 256x +2^-14 tiny per-step grads, -2^14, +1/128 coarse grad  (running sum M=2^14; each tau<ULP(M); exact g=0.0234375) */
/*   exact g = 3/128 = 0.0234375 ; quire readout 0x2a00 = 0.0234375 (EXACT) ; fp32 running sum = 0.0078125 (0x3c000000) ; fp32 LOSES 66.7% of g */
static const int32_t QGRAD_GRAD_ACCUM_T256_CODES[] = {
    0x6c00, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400, 0x1400,
    0x1400, 0x9400, 0x2400,
};
static const int QGRAD_GRAD_ACCUM_T256_N = (int)(sizeof(QGRAD_GRAD_ACCUM_T256_CODES)/sizeof(QGRAD_GRAD_ACCUM_T256_CODES[0]));
static const int QGRAD_GRAD_ACCUM_T256_T = 256;  /* number of tiny per-step grads */
static const uint32_t QGRAD_GRAD_ACCUM_T256_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0x06000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char QGRAD_GRAD_ACCUM_T256_QUIRE_HEX[] = "0000000000000000000000060000000000000000000000000000000000000000";
static const int32_t QGRAD_GRAD_ACCUM_T256_READOUT_BP16 = 0x2a00;
static const uint32_t QGRAD_GRAD_ACCUM_T256_FP32_BITS = 0x3c000000u;  /* genuine fp32 running sum (loses tail) */
static const uint32_t QGRAD_GRAD_ACCUM_T256_EXACT_FP32_BITS = 0x3cc00000u;  /* fp32(exact gradient) -- the target fp32 missed */
static const int64_t QGRAD_GRAD_ACCUM_T256_EXACT_NUM = 3LL;
static const int64_t QGRAD_GRAD_ACCUM_T256_EXACT_DEN = 128LL;
static const char QGRAD_GRAD_ACCUM_T256_NAME[] = "grad_accum_T256";

/* ---- dispatch table: pointers into the per-case arrays ---- */
typedef struct {
    const char* name;
    const int32_t* codes;
    int n;
    int t_steps;                  /* number of tiny per-step grads */
    const uint32_t* quire;        /* 8 limbs LE */
    const char* quire_hex;
    int32_t readout_bp16;
    uint32_t fp32_bits;           /* genuine fp32 running sum */
    uint32_t exact_fp32_bits;     /* fp32(exact gradient) */
    int64_t exact_num;
    int64_t exact_den;
} qgrad_case_t;

static const qgrad_case_t QGRAD_CASES[] = {
    { QGRAD_GRAD_ACCUM_T64_NAME, QGRAD_GRAD_ACCUM_T64_CODES, QGRAD_GRAD_ACCUM_T64_N, QGRAD_GRAD_ACCUM_T64_T, QGRAD_GRAD_ACCUM_T64_QUIRE, QGRAD_GRAD_ACCUM_T64_QUIRE_HEX, QGRAD_GRAD_ACCUM_T64_READOUT_BP16, QGRAD_GRAD_ACCUM_T64_FP32_BITS, QGRAD_GRAD_ACCUM_T64_EXACT_FP32_BITS, QGRAD_GRAD_ACCUM_T64_EXACT_NUM, QGRAD_GRAD_ACCUM_T64_EXACT_DEN },
    { QGRAD_GRAD_ACCUM_T128_NAME, QGRAD_GRAD_ACCUM_T128_CODES, QGRAD_GRAD_ACCUM_T128_N, QGRAD_GRAD_ACCUM_T128_T, QGRAD_GRAD_ACCUM_T128_QUIRE, QGRAD_GRAD_ACCUM_T128_QUIRE_HEX, QGRAD_GRAD_ACCUM_T128_READOUT_BP16, QGRAD_GRAD_ACCUM_T128_FP32_BITS, QGRAD_GRAD_ACCUM_T128_EXACT_FP32_BITS, QGRAD_GRAD_ACCUM_T128_EXACT_NUM, QGRAD_GRAD_ACCUM_T128_EXACT_DEN },
    { QGRAD_GRAD_ACCUM_T192_NAME, QGRAD_GRAD_ACCUM_T192_CODES, QGRAD_GRAD_ACCUM_T192_N, QGRAD_GRAD_ACCUM_T192_T, QGRAD_GRAD_ACCUM_T192_QUIRE, QGRAD_GRAD_ACCUM_T192_QUIRE_HEX, QGRAD_GRAD_ACCUM_T192_READOUT_BP16, QGRAD_GRAD_ACCUM_T192_FP32_BITS, QGRAD_GRAD_ACCUM_T192_EXACT_FP32_BITS, QGRAD_GRAD_ACCUM_T192_EXACT_NUM, QGRAD_GRAD_ACCUM_T192_EXACT_DEN },
    { QGRAD_GRAD_ACCUM_T256_NAME, QGRAD_GRAD_ACCUM_T256_CODES, QGRAD_GRAD_ACCUM_T256_N, QGRAD_GRAD_ACCUM_T256_T, QGRAD_GRAD_ACCUM_T256_QUIRE, QGRAD_GRAD_ACCUM_T256_QUIRE_HEX, QGRAD_GRAD_ACCUM_T256_READOUT_BP16, QGRAD_GRAD_ACCUM_T256_FP32_BITS, QGRAD_GRAD_ACCUM_T256_EXACT_FP32_BITS, QGRAD_GRAD_ACCUM_T256_EXACT_NUM, QGRAD_GRAD_ACCUM_T256_EXACT_DEN },
};

#endif  /* QUIRE_GRADIENT_CASES_H */
