/* Copyright (c) 2026 Anomly, Inc.
 * SPDX-License-Identifier: Apache-2.0 */
/* attention_golden_cases.h — GENERATED by gen_attention_golden.py.
 * DO NOT hand-edit. attention under MASSIVE-ACTIVATION OUTLIERS:
 * one query q and J keys k_j (head_dim D=32). A few dims are huge
 * outlier products (+/-2^33) that EXACTLY cancel in each key's exact
 * dot, so the exact score is the small-dim signal; but a naive IEEE
 * fp32 dot loses that signal in the cancellation and FLIPS the softmax
 * argmax. Ground truth = oracle exact Fraction arithmetic
 * (bposit16_reference.py); exact 256-bit quire dot = bp16_prod_to_q256
 * accumulation + single readout (kernel/bp16_quire.h, bp16_encode.h);
 * fp32 baseline = genuine binary32 RTNE naive dot (struct round-trip).
 *
 * Per key the host gates: (1) device quire limbs + bp16 readout ==
 * baked exact quire/readout (quire score error 0 vs exact); (2) device
 * fp32 naive-dot bits == baked fp32 bits. Then it softmaxes the score
 * vectors and asserts exact/quire argmax != fp32 argmax (the FLIP).
 */
#ifndef ATTENTION_GOLDEN_CASES_H
#define ATTENTION_GOLDEN_CASES_H

#include <cstdint>

#define ATTN_D 32
#define ATTN_NKEYS 3

/* ---- query q (D codes) ---- */
static const int32_t ATTN_Q_CODES[ATTN_D] = {
    0x7100, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400,
    0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400,
    0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400,
    0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x3400, 0x7100, 0x3400,
};

/* ---- key 0: key0_strong_signal ---- */
/*   exact score = 59/16 = 3.6875 ; quire readout 0x4760 = 3.6875 (EXACT) ; fp32 naive dot = 0.0625 (0x3d800000) -- WRONG */
static const int32_t ATTN_K0_CODES[ATTN_D] = {
    0x7000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x9000, 0x3c00,
};
static const uint32_t ATTN_K0_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0xb0000000u, 0x00000003u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char ATTN_K0_QUIRE_HEX[] = "0000000000000000000000b00300000000000000000000000000000000000000";
static const int32_t ATTN_K0_READOUT_BP16 = 0x4760;
static const uint32_t ATTN_K0_FP32_BITS = 0x3d800000u;  /* genuine fp32 naive dot */
static const int64_t ATTN_K0_EXACT_NUM = 59LL;
static const int64_t ATTN_K0_EXACT_DEN = 16LL;
static const char ATTN_K0_NAME[] = "key0_strong_signal";

/* ---- key 1: key1_mid_signal ---- */
/*   exact score = 19/8 = 2.375 ; quire readout 0x44c0 = 2.375 (EXACT) ; fp32 naive dot = 0.25 (0x3e800000) -- WRONG */
static const int32_t ATTN_K1_CODES[ATTN_D] = {
    0x7000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0xc000, 0xc000, 0xc000, 0xc000, 0xc000, 0xc000, 0x9000, 0x4400,
};
static const uint32_t ATTN_K1_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0x60000000u, 0x00000002u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char ATTN_K1_QUIRE_HEX[] = "0000000000000000000000600200000000000000000000000000000000000000";
static const int32_t ATTN_K1_READOUT_BP16 = 0x44c0;
static const uint32_t ATTN_K1_FP32_BITS = 0x3e800000u;  /* genuine fp32 naive dot */
static const int64_t ATTN_K1_EXACT_NUM = 19LL;
static const int64_t ATTN_K1_EXACT_DEN = 8LL;
static const char ATTN_K1_NAME[] = "key1_mid_signal";

/* ---- key 2: key2_weak_signal_big_tail ---- */
/*   exact score = 21/8 = 2.625 ; quire readout 0x4540 = 2.625 (EXACT) ; fp32 naive dot = 1.0 (0x3f800000) -- WRONG */
static const int32_t ATTN_K2_CODES[ATTN_D] = {
    0x7000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000,
    0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0x4000, 0xc000, 0xc000,
    0xc000, 0xc000, 0xc000, 0xc000, 0xc000, 0xc000, 0x9000, 0x4c00,
};
static const uint32_t ATTN_K2_QUIRE[8] = {
    0x00000000u, 0x00000000u, 0xa0000000u, 0x00000002u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const char ATTN_K2_QUIRE_HEX[] = "0000000000000000000000a00200000000000000000000000000000000000000";
static const int32_t ATTN_K2_READOUT_BP16 = 0x4540;
static const uint32_t ATTN_K2_FP32_BITS = 0x3f800000u;  /* genuine fp32 naive dot */
static const int64_t ATTN_K2_EXACT_NUM = 21LL;
static const int64_t ATTN_K2_EXACT_DEN = 8LL;
static const char ATTN_K2_NAME[] = "key2_weak_signal_big_tail";

typedef struct {
    const char* name;
    const int32_t* codes;        /* D key codes */
    const uint32_t* quire;       /* 8 limbs LE (exact quire dot q.k) */
    const char* quire_hex;
    int32_t readout_bp16;        /* quire dot -> bp16 (== exact score) */
    uint32_t fp32_bits;          /* genuine fp32 naive dot */
    int64_t exact_num;
    int64_t exact_den;
} attn_key_t;

static const attn_key_t ATTN_KEYS[ATTN_NKEYS] = {
    { ATTN_K0_NAME, ATTN_K0_CODES, ATTN_K0_QUIRE, ATTN_K0_QUIRE_HEX, ATTN_K0_READOUT_BP16, ATTN_K0_FP32_BITS, ATTN_K0_EXACT_NUM, ATTN_K0_EXACT_DEN },
    { ATTN_K1_NAME, ATTN_K1_CODES, ATTN_K1_QUIRE, ATTN_K1_QUIRE_HEX, ATTN_K1_READOUT_BP16, ATTN_K1_FP32_BITS, ATTN_K1_EXACT_NUM, ATTN_K1_EXACT_DEN },
    { ATTN_K2_NAME, ATTN_K2_CODES, ATTN_K2_QUIRE, ATTN_K2_QUIRE_HEX, ATTN_K2_READOUT_BP16, ATTN_K2_FP32_BITS, ATTN_K2_EXACT_NUM, ATTN_K2_EXACT_DEN },
};

static const int ATTN_EXACT_ARGMAX = 0;  /* true winner (quire agrees) */
static const int ATTN_FP32_ARGMAX  = 2;  /* fp32 picks the WRONG key */

#endif  /* ATTENTION_GOLDEN_CASES_H */
