// Copyright (c) 2026 Anomly, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// bposit_qmac_tb — drives M dot products of length K through bposit_qmac and
// checks the accumulated 256-bit quire bit-for-bit against the reference
// (eq.hex, generated by gen_rtl_vectors.py from the Python reference == GPU).

module bposit_qmac_tb;
  `include "dims.svh"

  logic clk = 0, rst_n = 0, clr = 0, en = 0;
  logic [4:0] a, b;
  logic signed [255:0] quire;

  bposit_qmac dut (.clk_i(clk), .rst_ni(rst_n), .clr_i(clr), .en_i(en),
                   .a_i(a), .b_i(b), .quire_o(quire));

  always #5 clk = ~clk;

  logic [7:0]   a_mem [0:M*K-1];
  logic [7:0]   b_mem [0:M*K-1];
  logic [255:0] eq_mem [0:M-1];

  int fails = 0;
  initial begin
    $readmemh("a.hex", a_mem);
    $readmemh("b.hex", b_mem);
    $readmemh("eq.hex", eq_mem);
    rst_n = 0; @(posedge clk); @(posedge clk); rst_n = 1;
    for (int m = 0; m < M; m++) begin
      @(negedge clk); clr = 1; en = 0; @(negedge clk); clr = 0;   // zero the quire
      for (int k = 0; k < K; k++) begin
        a = a_mem[m*K+k][4:0]; b = b_mem[m*K+k][4:0]; en = 1;
        @(negedge clk);
      end
      en = 0; @(negedge clk);                                     // let last acc settle
      if (quire !== eq_mem[m]) begin
        fails++;
        if (fails <= 4) begin
          $display("  MISMATCH dot %0d:", m);
          $display("    got = %064x", quire);
          $display("    exp = %064x", eq_mem[m]);
        end
      end
    end
    $display("=== bposit_qmac: exact 256-bit quire vs reference ===");
    $display("Summary: %0d/%0d dot-product quires bit-exact", M-fails, M);
    $display("RESULT: %s", (fails==0) ? "PASS" : "FAIL");
    $finish;
  end
endmodule
